import type { NextPage } from 'next'
import Head from 'next/head'
import { GetServerSideProps,InferGetServerSidePropsType } from 'next';
import MoviesCollection from '../components/MoviesCollection';
import ShowsCollection from '../components/ShowCollections';
import GenreComp from '../components/Genre';
import UpcomingMovies from '../components/UpcomingMovies/Upcoming';
import GenreBar from '../components/GenreBar/GenreBar';

export interface MovieInterface{
  adult: boolean,
  backdrop_path:string,
  id:number,
  title:string,
  original_language:string,
  original_title:string,
  overview:string,
  poster_path:string,
  media_type:string,
  genre_ids:number[],
  popularity:number,
  release_date:string,
  video: false,
  vote_average:number,
  vote_count:number
}
export interface ShowInterface{
  adult: boolean,
  backdrop_path:string,
  id:number,
  name:string,
  original_language:string,
  original_name:string,
  overview:string,
  poster_path:string,
  media_type:string,
  genre_ids:number[],
  popularity:number,
  first_air_date:string,
  video: false,
  vote_average:number,
  vote_count:number
}
export type ApiResponse={
page:number,
results:MovieInterface[],
total_pages:string,
total_results:string
}

const key:string | undefined=process.env.NEXT_PUBLIC_API_KEY;

const Home: NextPage = ({trendingmovies,trendingshows}:InferGetServerSidePropsType<typeof getServerSideProps>) => {
  return (
    <>
      <Head>
        <title>Entertainment App</title>
        <meta name="description" content="Generated by create next app for all you movie needs" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GenreBar/>
      <MoviesCollection movies={trendingmovies.results} value={"Trending Movies"}/>
      <ShowsCollection movies={trendingshows.results} value={"Trending Shows"}/>
      <UpcomingMovies url={`https://api.themoviedb.org/3/movie/upcoming?api_key=${key}`}/>
      <GenreComp url={`https://api.themoviedb.org/3/discover/movie?api_key=${key}&with_genres=35`}  title='Comedy Movies'/>
      <GenreComp url={`https://api.themoviedb.org/3/discover/movie?api_key=${key}&with_genres=28`}  title='Actions Movies'/>
      <GenreComp url={`https://api.themoviedb.org/3/discover/movie?api_key=${key}&with_genres=27`}  title='Horror Movies'/>
      
      <div style={{marginBottom:'1rem',minHeight:'100px'}}></div>
    </>
  )
}

export const getServerSideProps:GetServerSideProps=async()=> {
  const res= await fetch(`https://api.themoviedb.org/3/trending/movie/day?api_key=${key}`)
  const trendingmovies:ApiResponse=await res.json()
  const ress= await fetch(`https://api.themoviedb.org/3/trending/tv/day?api_key=${key}`)
  const trendingshows:ApiResponse=await ress.json()
  
  return {
      props:{
        trendingmovies,
        trendingshows
      }
  }
  
}

export default Home
